blog/models.py
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash
from sqlalchemy import desc

from . import db

class BlogPost(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime, default=datetime.utcnow)
    title = db.Column(db.String(256), nullable=False)
    body = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    @staticmethod
    def get_by_id(id):
        return BlogPost.query.filter_by(id=id).first()

    @staticmethod
    def newest(num):
        return BlogPost.query.order_by(desc(BlogPost.date)).limit(num)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    password_hash = db.Column(db.String)
    blogposts = db.relationship("BlogPost", backref='user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('password: write-only field')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)
    
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    @staticmethod
    def get_by_username(username):
        return User.query.filter_by(username=username).first()
    
    def __repr__(self):
        return "<User '{}'>".format(self.username)

blog/__init__.py
from flask import Flask, Blueprint
from datetime import datetime
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_moment import Moment
from flask_debugtoolbar import DebugToolbarExtension
# from flask_webpack import Webpack
# from flask_babel import Babel
# from flask_cache import Cache

from blog.config import config_by_name

db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = "auth.login"

moment = Moment()

toolbar = DebugToolbarExtension()

#cache = Cache()
# babel = Babel()
# webpack = Webpack()

def create_app(config_name):
    print(config_name)
    app = Flask(__name__)
    app.config.from_object(config_by_name[config_name])
    db.init_app(app)
    login_manager.init_app(app)
    moment.init_app(app)
    toolbar.init_app(app)
    # babel.init_app(app)
    # webpack.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .posts import posts as posts_blueprint
    app.register_blueprint(posts_blueprint, url_prefix='/posts')

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .api import api as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix='/api')

    return app


#

blog/api/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

from . import views

blog/api/views.py
from flask import redirect, url_for, request, json, abort
from flask_login import login_required
from ..models import User, BlogPost
from .. import login_manager, db

from . import api

@login_manager.user_loader
def load_user(userid):
    return User.query.get(int(userid))

@api.route('/posts/<int:id>')
def get_posts(id):
    p = BlogPost.get_by_id(id)
    if p is not None:
        return json.jsonify({
            'id' : p.id,
            'title' : p.title,
            'body' : p.body,
            'user' : {
                'id' : p.user.id,
                'username' : p.user.username
            },
            'date' : p.date,
        })
    abort(404)

@api.route('/posts/add', methods=['POST'])
@login_required
def add_post():
    u = User.query.get(1)
    data = request.json
    p = BlogPost(user=u, title=data['title'], body=data['body'])
    db.session.add(p)
    db.session.flush()
    db.session.commit()
    #print(p.id)
    return str(p.id)

@api.route('/posts/edit/<int:id>', methods=['POST'])
@login_required
def edit_post(id):
    p = BlogPost.query.get(id)
    if p is None:
        abort(404)
    data = request.json
    p.title=data['title']
    p.body=data['body']
    db.session.commit()
    p = BlogPost.query.get(id)
    #print(p.id)
    return json.jsonify({
            'id' : p.id,
            'title' : p.title,
            'body' : p.body,
            'user' : {
                'id' : p.user.id,
                'username' : p.user.username
            },
            'date' : p.date,
        })



@api.route('/posts/delete/<int:id>', methods=['DELETE'])
@login_required
def delete_post(id):
    #print(id)
    p = BlogPost.query.get(int(id))
    if p is None:
        abort(404)
    db.session.delete(p)
    db.session.commit()
    return json.jsonify({
            'id' : p.id,
            'title' : p.title,
            'body' : p.body,
            'date' : p.date,
        })

blog/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

blog/main/views.py
from flask import Flask, render_template, url_for, request,redirect,flash
from . import main
from .. import login_manager
from ..models import User, BlogPost
from . import html2text

@login_manager.user_loader
def load_user(userid):
    return User.query.get(int(userid))

@main.route('/')
@main.route('/index')
def index():
    return render_template('index.html', new_blogposts=BlogPost.newest(3), blog_title="Chengyi's Blog", fn_html2text=html2text.html2text)

@main.route('/aboutme')
def aboutme():
    return redirect("https://www.linkedin.com/in/chengyi-wu/")

@main.app_errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

@main.app_errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

blog/posts/__init__.py
from flask import Blueprint

posts = Blueprint('posts', __name__)

from . import views

blog/posts/views.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_required
from blog.models import User
from blog import login_manager, db

from . import posts

@posts.route('/')
def index():
    return redirect(url_for("main.index"))

# Use JSON + RESTful
@posts.route('/add')
@login_required
def add():
    return render_template('add.html')

@posts.route('/edit')
@login_required
def edit():
    id = int(request.args.get('id'))
    return render_template('edit.html', id=id)

@posts.route('/<int:id>')
def view(id):
    return render_template('disp.html', id=id)

blog/templates/add.html
{% extends "base.html" %}

{% block title %}
    New Post
{% endblock %}

{% block content %}
    <style>
        .title-toolbar{
            display: none;
        }
        .editor-class {
            min-height: 500px;
            border: none;
        }
        .submit-button{
            font-family: Georgia,serif;
            float: right;
            border-color: #ccc;
            border-radius: 36px;
            padding: 10px 30px;
            -webkit-border-radius: 36px;
        }
    </style>
    <section>
        <!-- <h2 style="clear:both">Add a new Post</h2> -->
        <span id='blog-form' />
    </section>

    <script src="../static/dist/add.js"></script>

{% endblock %}

{%block sidebar%}
{%endblock%}

blog/templates/base.html
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="../static/css/normalize.min.css">
        <link rel="stylesheet" href="../static/css/main.css">

        <script src="../static/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
    </head>
    <body>

        <div class="header-container">
            <header class="wrapper clearfix">
                <a href="{{ url_for('main.index') }}" style="text-decoration:none;"><h1 class="title">Chengyi Wu's Blog</h1></a>
                <nav>
                    <ul>
                        <li><a href="{{ url_for('posts.add') }}">Add</a></li>
                        <li>
                            {% if current_user.is_authenticated %}
                                <a href="{{ url_for('auth.logout') }}">Sign Out</a>
                            {% else %}
                                <a href="{{ url_for('auth.login') }}">Sign In</a>
                            {% endif %}
                        </li>
                        <li><a href="{{ url_for('main.aboutme') }}">Me</a></li>
                    </ul>
                </nav>
            </header>
        </div>

        <div class="main-container">
            <div class="main wrapper clearfix">

                <article class="flashes">
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            <ul>
                                {% for message in messages %}
                                    <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    {% endwith %}
                </article>

                {% block content %}
                {% endblock %}
                
                {% block sidebar %}
                    <!-- <aside>
                        <h3>aside</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales urna non odio egestas tempor. Nunc vel vehicula ante. Etiam bibendum iaculis libero, eget molestie nisl pharetra in. In semper consequat est, eu porta velit mollis nec. Curabitur posuere enim eget turpis feugiat tempor. Etiam ullamcorper lorem dapibus velit suscipit ultrices.</p>
                    </aside> -->
                {% endblock %}





            </div> <!-- #main -->
        </div> <!-- #main-container -->

        <div class="footer-container">
            <footer class="wrapper">
                <div>&copy; {{ moment().format('YYYY') }} Chengyi Wu</div>
                <div>Powered by <a href="http://flask.pocoo.org/" target="_blank">Flask</a> &amp; <a href="https://reactjs.org/" target="_blank">React</a></div>
            </footer>
        </div>

        {{ moment.include_jquery() }}
        {{ moment.include_moment() }}
    </body>
</html>

blog/templates/blog_list.html
<ul class="blogposts">
    {% for blogpost in blogposts %}
        <li>
            <a class="header" href="/posts/{{ blogpost.id }}">
                <h3 class="blogtitle">
                    {{ blogpost.title|truncate(32, killwords=True) }}
                </h3>
            </a>
            <div class="blogbody">
                    {{ fn_html2text(blogpost.body) | truncate(300, killwords=True) }}
            </div>     

            <div class="info">
                Add {{ moment(blogpost.date).fromNow() }}.
            </div>
        </li>
    {% endfor %}
</ul>

blog/templates/disp.html
{% extends "base.html" %}

{% block title %}
    Blog
{% endblock %}

{% block content %}

    <article id="BlogPost">
       <!-- React Mount-->
    </article>
    <div id="blog-id" style="display:none;">{{ id }}</div>
    {% if current_user.is_authenticated %}
    <article id="authenticated-div"></article>
    {% endif %}


    <script src="../static/dist/disp.js"></script>

{% endblock %}

blog/templates/edit.html
{% extends "base.html" %}

{% block title %}
    Edit Post
{% endblock %}

{% block content %}

    <div id="blog-id" style="display:none;">{{ id }}</div>
    <section>
        <!-- <h2 style="clear:both">Add a new Post</h2> -->
        <span id='blog-form' />
    </section>

    <script src="../static/dist/edit.js"></script>

{% endblock %}

{%block sidebar%}
{%endblock%}

blog/templates/form_macros.html
{% macro render_field(field) %}
    <tr {% if field.errors %} class="error" {% endif %}>
        <td>{{ field.label }}</td>
        <td>{{ field(**kwargs)|safe }}</td>
    </tr>
    <tr class="error">
        <td></td>
        <td>
            <url>
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </url>
        </td>
    </tr>
{% endmacro %}

blog/templates/index.html
{% extends "base.html" %}

{% block title %}
    {{ blog_title }}
{% endblock %}

{% block content %}

    <article>
        <header>
            <!-- <h1>Blog</h1> -->
            <!-- <p>Flask + React</p> -->
        </header>
        <section>
            <h2>Recently added</h2>
            {% if new_blogposts.count() > 0 %}
                {% with blogposts = new_blogposts %}
                    {% include "blog_list.html" %}
                {% endwith %}
            {% else %}
                    No blogs have been posted yet
            {% endif %}
        </section>
            <!-- <footer>
                <h3>article footer h3</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales urna non odio egestas tempor. Nunc vel vehicula ante. Etiam bibendum iaculis libero, eget molestie nisl pharetra in. In semper consequat est, eu porta velit mollis nec. Curabitur posuere enim eget turpis feugiat tempor.</p>
            </footer> -->
    </article>

{% endblock %}

{% block sidebar %}
<aside>
    <script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
    <div class="LI-profile-badge"  data-version="v1" data-size="large" data-locale="en_US" data-type="horizontal" data-theme="light" data-vanity="chengyi-wu"><a class="LI-simple-link" href='https://cn.linkedin.com/in/chengyi-wu?trk=profile-badge'>Chengyi Wu</a></div>
</aside>
{% endblock %}

blog/templates/login.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
    Blog -- Login
{% endblock %}

{% block content %}
<!-- rewrite in react -->

    <section>
        <h1 style="clear:both">Please login</h1>
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <table>
                {{ render_field(form.username, size=50) }}
                {{ render_field(form.password, size=50) }}
                {{ render_field(form.remember_me) }}
                {{ render_field(form.submit) }}
            </table>
        </form>
    </section>

{% endblock %}

{%block sidebar%}
{%endblock%}